import assert from 'node:assert/strict';
import {playbackTrace} from './playback-trace.mjs';
const entries=[];
const p=playbackTrace(s=>entries.push(JSON.parse(s)),{epoch:()=>123456,monotonic:()=>4.5});
const result=await p.observe('PLAYBACK.RESET',()=>({queuedFramesCleared:3}));
assert.equal(result.queuedFramesCleared,3);
assert.equal(entries[0].trace.kind,'PLAYBACK.RESET.BEGIN');
assert.equal(entries[1].trace.queuedFramesCleared,3);
assert.equal(entries[1].trace.clientSequence,2);
await assert.rejects(p.observe('TRANSCRIPT.TRUNCATE',()=>{throw new Error('failed');}));
assert.equal(entries[3].trace.kind,'TRANSCRIPT.TRUNCATE.FAILED');
assert.equal(entries[3].trace.clientEpochMs,123456);
const broken=playbackTrace(()=>{throw new Error('socket closed');});
let reset=false;
await broken.observe('PLAYBACK.RESET',()=>{reset=true;});
assert.equal(reset,true);
assert.equal(broken.failedReports,2);
assert.throws(()=>broken.checkHealthy(),/Incomplete playback trace/);
console.log('PASS playback observation success/failure and client timing');
